export const data = [
    {
        id: 1,
        firstName: 'John ',
        lastName: 'Brown',
        date: ' 12/04/2021 10:00 AM',
        department: 'Cardiology',
        status: 'Active',
    },
    {
        id: 2,
        firstName: 'John ',
        lastName: 'Green',
        date: ' 12/06/2021 10:00 AM',
        department: 'Surgery',
        status: 'Accepted',
    },
    {
        id: 3,
        firstName: 'John ',
        lastName: 'Black',
        date: ' 10/05/2021 10:00 AM',
        department: 'Anesthetics',
        status: 'Rejected',
    },
    {
        id: 4,
        firstName: 'John ',
        lastName: 'Brown',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Active',
    },
    {
        id: 5,
        firstName: 'Anna ',
        lastName: 'Brown',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Rejected',
    }, {
        id: 6,
        firstName: 'John ',
        lastName: 'Brown',
        date: ' 12/04/2021 10:00 AM',
        department: 'Cardiology',
        status: 'Active',
    },
    {
        id: 7,
        firstName: 'Jim ',
        lastName: 'Green',
        date: ' 12/06/2021 10:00 AM',
        department: 'Surgery',
        status: 'Accepted',
    },
    {
        id: 8,
        firstName: 'Joe ',
        lastName: 'Black',
        date: ' 10/05/2021 10:00 AM',
        department: 'Anesthetics',
        status: 'Rejected',
    },
    {
        id: 9,
        firstName: 'John ',
        lastName: 'Wick',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Active',
    },
    {
        id: 10,
        firstName: 'Anna Wick',
        lastName: 'Wick',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Rejected',
    }, {
        id: 11,
        firstName: 'Anna',
        lastName: 'Wick',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Rejected',
    },
    {
        id: 12,
        firstName: 'Anna Wick',
        lastName: 'Wick',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Rejected',
    }, {
        id: 13,
        firstName: 'Anna',
        lastName: 'Wick',
        date: ' 10/02/2021 10:00 AM',
        department: 'Orthopedics',
        status: 'Rejected',
    },
];